Create magic mark initial design and login form
AnastasiyaPoleshuk/Magic-Marks pull request #2
Opened 2022-09-21 12:03 UTC by AnastasiyaPoleshuk

2022-09-21 14:03 UTC, AyvengoBY requested changes

2022-09-21 14:03 UTC, AyvengoBY commented on magic-marks/src/api/loginAPI.ts
> +const createUser = async (data: ILoginFormData) => {
Rename to LoginUser, please.

2022-09-21 14:03 UTC, AyvengoBY commented on magic-marks/src/components/LoginForm/LoginForm.tsx
> +            *Длина пароля должна быть не меньше 3 символов
Please move all text values  into constants. For this purpose, please create locales/ru-Ru/index.json  file with localized string constunts (this file will be used for possible localization purpose using i18 package)

2022-09-21 14:03 UTC, AyvengoBY commented on magic-marks/src/views/main/Main.tsx
> +              Приложение позволяет просматривать оценки,
Move into constants, please

2022-09-21 14:03 UTC, AyvengoBY commented on magic-marks/src/views/main/Main.tsx
> +      {isOpenModal
Is this code can support different modals ? (Or Login modal only)

2022-09-21 15:36 UTC, AnastasiyaPoleshuk commented on magic-marks/src/api/loginAPI.ts
> +const createUser = async (data: ILoginFormData) => {
changed

2022-09-21 15:36 UTC, AnastasiyaPoleshuk commented on magic-marks/src/components/LoginForm/LoginForm.tsx
> +            *Длина пароля должна быть не меньше 3 символов
done

2022-09-21 15:36 UTC, AnastasiyaPoleshuk commented on magic-marks/src/views/main/Main.tsx
> +              Приложение позволяет просматривать оценки,
done

2022-09-21 15:36 UTC, AnastasiyaPoleshuk commented on magic-marks/src/views/main/Main.tsx
> +      {isOpenModal
yes

2022-09-26 08:52 UTC, AyvengoBY approved these changes

2022-09-26 10:38 UTC, merged